remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

title: Art and Design Portfolio
description: A series of artworks created by Kal Corwin, selected and arranged in order to demonstrate the evolution of his understanding of design.
